# # Tells H2 to save data in a file folder called 'data' in your project
# spring.datasource.url=jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

# # Tells Spring to automatically create database tables based on your Java code
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # Enables a web dashboard so you can view your database if you want to
# spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/Ajay/Desktop/data/bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true